<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="libs\**" />
    <EmbeddedResource Remove="libs\**" />
    <None Remove="libs\**" />
    <Page Remove="libs\**" />
  </ItemGroup>

  <ItemGroup>
    <COMReference Include="ActProgTypeLib">
      <VersionMinor>0</VersionMinor>
      <VersionMajor>1</VersionMajor>
      <Guid>cd7846df-1c99-4bc0-8a8d-fbfb7fc26acb</Guid>
      <Lcid>0</Lcid>
      <WrapperTool>tlbimp</WrapperTool>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </COMReference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="References\" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="ActUtlTypeLib">
      <HintPath>libs\ActUtlTypeLib.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
